### ISSUE TITLE
Users can select a city to view its Quality of Life ratings

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#1]
## 💰 Motivation

Users want to be able to see Quality of Life ratings for select cities

## 📐 Plan

Create a form for city to be selected, user submits request

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/98700787-6e8a7400-232d-11eb-8322-7860d41451b9.png)

## ✅ Task List

- [x] Pick font
- [x] Set up Header
- [x] Create list of radio buttons with choice of cities
- [x] Create button which fetches results through Api call
- [x] Create footer bar with nav links
- [x] Test
- [x] Remove any unnecessary code
