### ISSUE TITLE
Users can insert any city in textbox

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#13]
## 💰 Motivation

Users want to be able to view the quality ratings for any city available through the api

## 📐 Plan

Create a textbox, check the api if such a city exists, then get data

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/99111764-8a964b80-25a1-11eb-9704-d42f2449c02c.png)

## ✅ Task List

- [x] Create textbox and modify header instructions
- [x] Set up eventListener to call api for checking city
- [x] Display message if no city found
- [x] Allow the user to submit the form
- [x] Make sure table displays information properly
- [x] Test 
- [x] Remove any unnecessary code
