### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#17]
## 💰 Motivation

We need to handle errors and display api call in progress

## 📐 Plan

Display to the user if information is not able to be retrieved / api call is in progress with spinner

## ✅ Task List

- [x] Form should be disabled while api is being called
- [x] Notify the user if there is an error with the request
- [x] Notify the user if no data has been returned
- [x] Notify the user that an api request is in progress
- [x] Test
