### ISSUE TITLE
Users can view ratings for the selected city

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#2]
## 💰 Motivation

Users want to be able to see Quality of Life ratings for the selected city

## 📐 Plan

Create a table which will display the info retrieved from the API call

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/98700929-97126e00-232d-11eb-8a0f-9d49d7bc5106.png)

## ✅ Task List

- [x] Add eventlistener for submit that calls API
- [x] Create a data model
- [x] Create a new data-view for results
- [x] Display the requested info through use of a table
- [x] Create add to favorites button
- [x] Create a view swapping function
- [x] Add eventlistener on footer which returns to the main page
- [x] Test
- [x] Remove any unnecessary code
