### ISSUE TITLE
Users can save cities in a favorites list and view the list

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#3]
## 💰 Motivation

Users want to be able to select cities as favorite

## 📐 Plan

Add eventListener to favorites button and create page which displays favorite cities

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/98701050-b7422d00-232d-11eb-8251-117c7cdddf30.png)
______________________________________________________________________
![image](https://user-images.githubusercontent.com/57933609/98701143-ce811a80-232d-11eb-8a44-ebc16779bde1.png)

## ✅ Task List

- [x] Add eventListener on add to favorites
- [x] Change the text of the button when user clicks
- [x] Add it to list of favorites
- [x] Disable the button
- [x] Create view for favorites
- [x] Use list to display favorites
- [x] Add eventListener on nav bar which takes user to favorites page
- [x] Test
- [x] Remove any unnecessary code
