### ISSUE TITLE
Users can delete cities in a favorites list

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#4]
## 💰 Motivation

Users want to be able to delete a favorite city

## 📐 Plan

Users can click a delete button which deletes that city

## ✅ Task List

- [x] Add eventlistener on delete buttons
- [x] Delete the city which the user selected 
- [x] Remove it from the dom
- [x] Test
- [x] Remove any unnecessary code
