### ISSUE TITLE
Users can compare cities ratings

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#5]
## 💰 Motivation

Users want to be able to compare the quality ratings of two cities

## 📐 Plan

Create a form that has two radio button sections for two cities

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/98701341-0720f400-232e-11eb-8b9f-b600bf22b6a6.png)

## ✅ Task List

- [x] Create a form with two radio sections
- [x] Add an event handler on the nav button compare to navigate to this page
- [x] Figure out way that user cannot select the same city on both sides
- [x] Test
- [x] Remove any unnecessary code
