### ISSUE TITLE
Users can view the compared cities ratings

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/ajax-project#6]
## 💰 Motivation

Users want to be able to view the quality ratings of the two cities

## 📐 Plan

Create a display which displays the two city ratings graphically

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/57933609/98701440-228bff00-232e-11eb-85b7-f6cf013a5ec0.png)

## ✅ Task List

- [x] Capture the user data on submit
- [x] Make 2 api calls to fetch the data
- [x] Create a new view for the results
- [x] Update table to display current information
- [x] Do a compare on values, and assign colors appropriately
- [x] Test 
- [x] Remove any unnecessary code
